config:
  aws:region: us-east-1
  dagster-poc-infra:environment: dev
  dagster-poc-infra:vpcId: vpc-063bc9a57fb3fe72d
  dagster-poc-infra:subnetIds:
    - subnet-011694f92eaa64be2
    - subnet-0d975036880e8b19d
encryptionsalt: v1:F0POiK4IAh4=:v1:QWZb0zUNjc3uLWkA:i2hndNubmbYbwsyqWuT/GMiBsXpi5g==
